openapi: 3.0.3
info:
  title: OpenAPI schema for External-DNS template .
components:
  schemas:
    variables:
      type: object
      required:
      - cloudflare_api_token
      - txt_owner_id
      properties:
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where resources will be created.
          default: external-dns
          x-walrus-ui:
            group: Basic
            order: 1
        helm_release_name:
          title: Helm Release Name
          type: string
          description: The name of the Helm release.
          default: external-dns-cloudflare
          x-walrus-ui:
            group: Basic
            order: 2
        helm_chart_version:
          title: Helm Chart Version
          type: string
          description: The version of the Helm chart.
          default: 8.3.7
          x-walrus-ui:
            group: Basic
            order: 3
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for the External-DNS Helm release.
          default:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 1000m
              memory: 256Mi
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
        cloudflare_api_token:
          title: Cloudflare Api Token
          type: string
          description: The Cloudflare API token, base64-encoded.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 5
        txt_owner_id:
          title: Txt Owner Id
          type: string
          description: Cluster name for TXT owner ID.
          x-walrus-ui:
            group: Basic
            order: 6
      x-walrus-ui:
        groupOrder:
        - Basic
